/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List countries
         * @description Get all active countries with their statistics and feature flags.
         */
        get: operations["87b1e43e1fee480e4db58b462bf951c0"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Check if the API is running and responsive.
         */
        get: operations["46eba9cc4a2b9821366af012599e858d"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{locale}-{country}/allergens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List allergens
         * @description Get all allergens available for the current country. Allergens include common food allergens like gluten, dairy, nuts, etc.
         */
        get: operations["6dbf9abc9e0f9eaa41c7f26f4cfec49c"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{locale}-{country}/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List ingredients
         * @description Get all ingredients available for the current country. Each ingredient includes its localized name and image.
         */
        get: operations["4a4331e1b678f1df80fbf009a54415d8"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{locale}-{country}/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List labels
         * @description Get all labels available for the current country. Labels are promotional badges (e.g., \"New\", \"Best seller\") with associated colors.
         */
        get: operations["4adccf1a7e73829f2c185404e6409627"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{locale}-{country}/menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List menus
         * @description Get a paginated list of weekly menus for the current country. Optionally include recipes with the include_recipes parameter.
         */
        get: operations["d6cad478650564cf2be8117d42aaf595"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{locale}-{country}/menus/{year_week}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a menu
         * @description Get a single weekly menu with its recipes for the given year_week.
         */
        get: operations["117d430a405015b10d20701061a5a7b9"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{locale}-{country}/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List recipes
         * @description Get a paginated list of recipes for the current country and locale. Supports filtering by search term, tag, label, difficulty, and PDF availability.
         */
        get: operations["66515aaed21fa1e289884a3e079921f8"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{locale}-{country}/recipes/{recipe}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a recipe
         * @description Get a single recipe with all relations including steps, nutrition, ingredients, allergens, tags, cuisines, and utensils.
         */
        get: operations["a55d74edd776e81c1e9b6d152f76e355"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{locale}-{country}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tags
         * @description Get all tags available for the current country. Tags include dietary preferences, cooking styles, and meal characteristics.
         */
        get: operations["7fc25c11bcffccae725e8986d6f5862a"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AllergenCollection: {
            data?: components["schemas"]["AllergenResource"][];
        };
        AllergenResource: {
            id?: number;
            name?: string;
            icon_path?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CountryCollection: {
            data?: components["schemas"]["CountryResource"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        CountryResource: {
            id?: number;
            code?: string;
            domain?: string;
            locales?: string[];
            active?: boolean;
            take?: number | null;
            prep_min?: number | null;
            prep_max?: number | null;
            total_min?: number | null;
            total_max?: number | null;
            recipes_count?: number;
            recipes_with_pdf_count?: number;
            ingredients_count?: number;
            has_allergens?: boolean;
            has_cuisines?: boolean;
            has_labels?: boolean;
            has_tags?: boolean;
            has_utensils?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CuisineResource: {
            id?: number;
            name?: string;
            icon_path?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        IngredientCollection: {
            data?: components["schemas"]["IngredientResource"][];
        };
        IngredientResource: {
            id?: number;
            name?: string;
            image_path?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        LabelCollection: {
            data?: components["schemas"]["LabelResource"][];
        };
        LabelResource: {
            id?: number;
            name?: string;
            handles?: string | null;
            foreground_color?: string | null;
            background_color?: string | null;
            display_label?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        MenuCollection: {
            data?: components["schemas"]["MenuResource"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        MenuResource: {
            id?: number;
            url?: string;
            year_week?: string;
            /** Format: date */
            start?: string;
            recipes?: components["schemas"]["RecipeCollectionResource"][] | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        RecipeCollection: {
            data?: components["schemas"]["RecipeCollectionResource"][];
            meta?: components["schemas"]["PaginationMeta"];
        };
        RecipeCollectionResource: {
            id?: number;
            canonical_id?: number | null;
            published?: boolean;
            variant?: string | null;
            url?: string;
            name?: string;
            headline?: string | null;
            description?: string | null;
            difficulty?: number | null;
            prep_time?: number | null;
            total_time?: number | null;
            card_image_url?: string | null;
            header_image_url?: string | null;
            pdf_url?: string | null;
            has_pdf?: boolean;
            nutrition?: Record<string, never> | null;
            yields?: Record<string, never> | null;
            steps?: Record<string, never>[] | null;
            /** Format: date-time */
            hellofresh_created_at?: string | null;
            /** Format: date-time */
            hellofresh_updated_at?: string | null;
            label?: components["schemas"]["LabelResource"] | null;
            tags?: components["schemas"]["TagResource"][] | null;
            allergens?: components["schemas"]["AllergenResource"][] | null;
            ingredients?: components["schemas"]["IngredientResource"][] | null;
            cuisines?: components["schemas"]["CuisineResource"][] | null;
            utensils?: components["schemas"]["UtensilResource"][] | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        RecipeResource: {
            id?: number;
            canonical_id?: number | null;
            published?: boolean;
            variant?: string | null;
            url?: string;
            name?: string;
            headline?: string | null;
            description?: string | null;
            difficulty?: number | null;
            prep_time?: number | null;
            total_time?: number | null;
            card_image_url?: string | null;
            header_image_url?: string | null;
            pdf_url?: string | null;
            has_pdf?: boolean;
            nutrition?: Record<string, never> | null;
            yields?: Record<string, never> | null;
            steps?: Record<string, never>[] | null;
            /** Format: date-time */
            hellofresh_created_at?: string | null;
            /** Format: date-time */
            hellofresh_updated_at?: string | null;
            label?: components["schemas"]["LabelResource"] | null;
            tags?: components["schemas"]["TagResource"][] | null;
            allergens?: components["schemas"]["AllergenResource"][] | null;
            ingredients?: components["schemas"]["IngredientResource"][] | null;
            cuisines?: components["schemas"]["CuisineResource"][] | null;
            utensils?: components["schemas"]["UtensilResource"][] | null;
            saved_in_lists?: Record<string, never>[] | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        TagCollection: {
            data?: components["schemas"]["TagResource"][];
        };
        TagResource: {
            id?: number;
            name?: string;
            display_label?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        UtensilResource: {
            id?: number;
            name?: string;
            type?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        PaginationMeta: {
            current_page?: number;
            last_page?: number;
            per_page?: number;
            total?: number;
            from?: number | null;
            to?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "87b1e43e1fee480e4db58b462bf951c0": {
        parameters: {
            query?: {
                /** @description Items per page (10-200) */
                per_page?: number;
                /** @description Page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of active countries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryCollection"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "46eba9cc4a2b9821366af012599e858d": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is running */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message?: string;
                    };
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "6dbf9abc9e0f9eaa41c7f26f4cfec49c": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Language code (e.g., en, de, fr) */
                locale: string;
                /** @description Country code (e.g., US, DE, FR) */
                country: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of allergens */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllergenCollection"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "4a4331e1b678f1df80fbf009a54415d8": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Language code (e.g., en, de, fr) */
                locale: string;
                /** @description Country code (e.g., US, DE, FR) */
                country: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of ingredients */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientCollection"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "4adccf1a7e73829f2c185404e6409627": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Language code (e.g., en, de, fr) */
                locale: string;
                /** @description Country code (e.g., US, DE, FR) */
                country: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of labels */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelCollection"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    d6cad478650564cf2be8117d42aaf595: {
        parameters: {
            query?: {
                /** @description Items per page (10-200) */
                per_page?: number;
                /** @description Page number */
                page?: number;
                /** @description Include recipes in the response */
                include_recipes?: boolean;
                /** @description Filter menus starting from date (Y-m-d) */
                from?: string;
                /** @description Filter menus until date (Y-m-d) */
                to?: string;
            };
            header?: never;
            path: {
                /** @description Language code (e.g., en, de, fr) */
                locale: string;
                /** @description Country code (e.g., US, DE, FR) */
                country: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of menus */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuCollection"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "117d430a405015b10d20701061a5a7b9": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Language code (e.g., en, de, fr) */
                locale: string;
                /** @description Country code (e.g., US, DE, FR) */
                country: string;
                /** @description Year and week number (e.g., 202515) */
                year_week: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Menu details with recipes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuResource"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Menu not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "66515aaed21fa1e289884a3e079921f8": {
        parameters: {
            query?: {
                /** @description Items per page (10-200) */
                per_page?: number;
                /** @description Page number */
                page?: number;
                /** @description Full-text search in name, headline, and description */
                search?: string;
                /** @description Filter by tag ID */
                tag?: number;
                /** @description Filter by label ID */
                label?: number;
                /** @description Filter by difficulty level (1-3) */
                difficulty?: number;
                /** @description Filter recipes with PDF */
                has_pdf?: boolean;
                /** @description Sort field (created_at, updated_at) */
                sort?: string;
            };
            header?: never;
            path: {
                /** @description Language code (e.g., en, de, fr) */
                locale: string;
                /** @description Country code (e.g., US, DE, FR) */
                country: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of recipes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeCollection"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    a55d74edd776e81c1e9b6d152f76e355: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Language code (e.g., en, de, fr) */
                locale: string;
                /** @description Country code (e.g., US, DE, FR) */
                country: string;
                /** @description Recipe ID */
                recipe: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recipe details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResource"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Recipe not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "7fc25c11bcffccae725e8986d6f5862a": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Language code (e.g., en, de, fr) */
                locale: string;
                /** @description Country code (e.g., US, DE, FR) */
                country: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagCollection"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
